development:
  :address: smtp.gmail.com
  :port: 587
  :authentication: plain
  :user_name: seatslasher@gmail.com
  :password: password!123
  :enable_starttls_auto: true
production:
  :address: smtp.gmail.com
  :port: 587
  :authentication: plain
  :user_name: seatslasher@gmail.com
  :password: password!123
  :enable_starttls_auto: true
